# Generated by Django 4.0.4 on 2022-07-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('rua', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=25)),
                ('pais', models.CharField(max_length=15)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GeocodeSearch',
                'verbose_name_plural': 'GeocodeSearch',
                'ordering': ('cep',),
            },
        ),
    ]
